server:
  port: 8081
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security2?serverTimezone=Asia/Seoul
    username: cos
    password: cos1234
  security:
    oauth2:
      client:
        registration:
          # 카카오 설정
          kakao:
            client-id: df14d13f783d392d0793bf1da3d27554
            client-secret: XX9uj4dugP7lgs8zO5J0RQFhpHrrNJCO
            client-authentication-method: client_secret_post
            redirect-uri: "{baseUrl}/login/oauth2/code/kakao"
            authorization-grant-type: authorization_code
            client-name: kakao
            scope: profile_nickname, profile_image, account_email
          # 구글 설정
          google:
            provider: google
            client-id: 729344324932-1pei60u5r58ab0rfl4mrup668d5q9th7.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
          # Naver 설정
          naver:
            provider: naver
            client-id: oNJrYV_fWuUDM9Rt5djz
            client-secret: m_lVU7jF0n
            scope:
              - name
              - email
              - profile_image
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/naver"
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response


  mvc:
    view:
      prefix: /templates/
      suffix: .mustache

  jpa:
    hibernate:
      ddl-auto: update #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true


logging:
  level:
    org:
      springframework:
        security: DEBUG